Create experiment docu for container-kill
litmuschaos/v1-litmus-docs pull request #102
Opened 2019-12-02 10:24 UTC by LaumiH

This PR adds the container-kill experiment to the experiments docu. I added a note referring to [this issue/feature request](https://github.com/litmuschaos/litmus/issues/969).

2019-12-02 11:06 UTC, ksatchit submitted a review, later dismissed
/lgtm

2019-12-02 17:08 UTC, chandankumar4 commented on docs/container-kill.md
> +- View pod terminations & recovery by setting up a watch on the pods in the application namespace
This line more looks line pod-delete. This can be written as **View restarts count by setting up a watch on the pods in the application namespace**

2019-12-02 17:09 UTC, chandankumar4 commented on docs/container-kill.md
> +- Check whether the application is resilient to the pod failure, once the experiment (job) is completed. The ChaosResult resource name is derived like this: `<ChaosEngine-Name>-<ChaosExperiment-Name>
Instead of `pod failure` it should be **container kill**

2019-12-02 17:09 UTC, chandankumar4 commented on docs/container-kill.md
> +## Application Pod Failure Demo
Application container kill Demo

2019-12-02 17:11 UTC, chandankumar4 requested changes
Thanks, @LaumiH for your contribution towards container kill experiment, I have some review comment please have a look.

2019-12-03 05:10 UTC, ajeshbaby commented on docs/container-kill.md
> +- A sample recording of this experiment execution is provided here.
Lets add a [Todo] here, to state we don't have one right now.

2019-12-03 05:11 UTC, ajeshbaby commented on docs/container-kill.md
> +- A sample recording of this experiment execution is provided here.
Other wise looks good for me. We can merge post the above changes.

2019-12-04 09:23 UTC, ksatchit approved these changes

2019-12-04 09:32 UTC, ajeshbaby approved these changes
LGTM

2019-12-04 09:34 UTC, merged