Pod network latency - Litmus chaos experiment documents
litmuschaos/v1-litmus-docs pull request #109
Opened 2019-12-09 08:17 UTC by ashish-uiet

Pod Network Latency Experiment -- Litmus chaos documents

2019-12-09 16:31 UTC, ksatchit commented on docs/pod-network-latency.md
> +- Experimenting Cluster should be non-minikube cluster
Can we put this as a note in the pre-requisites that minikube is not supported & also change the tested K8s platform to the actual ones (you can refer to the pod-delete/container-kill cases). Right now it is a bit contradictory (Any/Minikube not supported) We can discuss addition of a `supported platforms` section to encourage the community.

2019-12-09 16:32 UTC, ksatchit commented on docs/pod-network-latency.md
> +- Application subjected to chaos must have tc network traffic shaping tool installed
Application container

2019-12-09 16:34 UTC, ksatchit commented on docs/pod-network-latency.md
> +
Lets add a note to say that the experiment is supported only on Docker Runtime. We do not support containerd/CRIO runtimes yet for network tests. There is a way for us to directly invoke `tc`, but these utils aren't added yet.

2019-12-09 16:36 UTC, ksatchit commented on docs/pod-network-latency.md
> +- The test involved setting up a ping to general/public IPs from inside the pod & also setting up a ping to the pod IP itself from a cluster node.
Not sure if the test needs to find a mention. The users of the experiment might have their own ways to detect the chaos injected. However, if you really feel like adding this, lets add a section on `example test` where you describe how it can be done.

2019-12-09 16:38 UTC, ksatchit commented on docs/pod-network-latency.md
> +- Causes flaky access to application replica by injecting network delay using pumba.
Probably add some more description from these points: 

- Injects latency on the specified container by starting a traffic control (`tc`) process with netem rules to add egress delays
- Latency is injected via pumba library with command `pumba netem delay` by passing the relevant network interface, latency, chaos duration and regex filter for container name
- Pumba is run as a daemonset on all nodes in dry-run mode to begin with; the latency command is issued during experiment execution via kubectl exec
Can test the application's resilience to lossy/flaky network

2019-12-09 16:40 UTC, ksatchit commented on docs/pod-network-latency.md
> +| TOTAL_CHAOS_DURATION  | The time duration for chaos insertion (seconds)              | Mandatory  | 60000                                            |
TOTAL_CHAOS_DURATION & NETWORK_LATENCY have default values. Hence Optional. The target container, network interface are generally unknown/instance-specific entities. These mandatory ENVs can probably be grouped upfront followed by the Optional ones

2019-12-09 16:41 UTC, ksatchit commented on docs/pod-network-latency.md
> +  name: engine-nginx
Lets probably name it nginx-chaos OR nginx-network-chaos

2019-12-09 16:44 UTC, ksatchit commented on docs/pod-network-latency.md
> +          value: nginx-deploy-container
lets take a look at other experiments, such as the container-kill where an nginx is being used as the sample application. Lets use the same application specs to keep the doc consistent/homogeneous. Say, someone installs the nginx app as recommended in docs  - they should be able to pick the sample chaosEngines to just work!

2019-12-09 16:46 UTC, ksatchit commented on docs/pod-network-latency.md
> +### Test Chaos progress
Watch Chaos Progress

2019-12-09 16:46 UTC, ksatchit commented on docs/pod-network-latency.md
> +### Test Chaos progress
The section is expected before the Check Chaos Experiment Result

2019-12-09 16:47 UTC, ksatchit commented on docs/pod-network-latency.md
> +- During Chaos progress interval View Pod Network Latency inside targeted container , By setting Up Traffic control (tc) tool in targeted container .Check Ping Simulate Internet connections.
```suggestion
- View network latency by setting up a ping on the affected pod from the cluster nodes 
```

2019-12-09 16:48 UTC, ksatchit commented on docs/pod-network-loss.md
> +- Experimenting Cluster should be non-minikube cluster
Please refer to comments in the network-delay experiment

2019-12-09 16:48 UTC, ksatchit commented on docs/pod-network-loss.md
> +- Pod-network-loss contains chaos to disrupt network connectivity of kubernetes pods.
```suggestion
- Pod-network-loss injects chaos to disrupt network connectivity to kubernetes pods.
```

2019-12-09 16:51 UTC, ksatchit requested changes
Thanks for the contribution @ashish-uiet !! Please take a look at the comments. Applies on the latency experiment docs applies to the network loss doc too!

2019-12-10 06:28 UTC, ashish-uiet commented on docs/pod-network-latency.md
> +          value: nginx-deploy-container
okay

2019-12-10 09:37 UTC, LaumiH commented on docs/pod-network-latency.md
> +
Let's also add that on minikube, the container must be priviledged, otherwise it has no permissions to mess with tc netem ...

2019-12-10 09:40 UTC, LaumiH commented on docs/pod-network-loss.md
> +- Experimenting Cluster should be non-minikube cluster
We can now change it to: minikube is supported (as soon as my pr gets merged), but the container must be priviledged in order to be allowed to use the tc netem command.

2019-12-10 09:41 UTC, LaumiH commented on docs/pod-network-latency.md
> +
So same as with the loss experiment: minikube works as soon as my pr gets merged by them, but the container must be privileged in order to execute the tc netem command.

2019-12-11 10:47 UTC, ajeshbaby commented on docs/pod-network-loss.md
> +        - name: TARGET_CONTAINER
Add a comment to update with container name of application where chaos has to be injected.

2019-12-11 10:47 UTC, ajeshbaby commented on docs/pod-network-loss.md
> +        - name: NETWORK_INTERFACE
Add a comment to update with interface inside the pod, there can be chances where it can be other than eth0

2019-12-12 11:04 UTC, ksatchit commented on website/sidebars.json
> +          "pod-delete",
can you add container-kill doc also here?

2019-12-13 04:21 UTC, ksatchit commented on docs/pod-network-latency.md
> +title: Pod Network Latency Experiment Detail
Details

2019-12-13 04:21 UTC, ksatchit commented on docs/pod-network-latency.md
> +- Application subjected to chaos must have tc network traffic shaping tool installed
With our new enhancements based  on 0.6.5, we longer depend on tc

2019-12-13 04:22 UTC, ksatchit commented on docs/pod-network-latency.md
> +
@ashish-uiet can you take care of the above?

2019-12-13 04:22 UTC, ksatchit commented on docs/pod-network-latency.md
> +| NETWORK_INTERFACE     | Name of ethernet interface considered for shaping traffic                                | Instance-Specific (Optional)  |   |
Target Container and Network Interface can be made mandatory.

2019-12-13 04:23 UTC, ksatchit commented on docs/pod-network-latency.md
> +#### Sample ChaosEngine Manifest
Like discussed, please change this to nginx

2019-12-13 04:23 UTC, ksatchit commented on docs/pod-network-latency.md
> +    `ping http_address`
can we change this to`ping <pod_ip_address`

2019-12-13 05:27 UTC, ashish-uiet commented on docs/pod-network-latency.md
> +- Application subjected to chaos must have tc network traffic shaping tool installed
removed 16th line

2019-12-13 05:36 UTC, ashish-uiet commented on docs/pod-network-latency.md
> +#### Sample ChaosEngine Manifest
done

2019-12-13 05:44 UTC, ashish-uiet commented on docs/pod-network-latency.md
> +    `ping http_address`
done

2019-12-13 06:38 UTC, ashish-uiet commented on docs/pod-network-latency.md
> +
waiting for code merge @LaumiH .
as of now checked in minikube following conf but not injecting chaos -
image - ksatchit/ansible-runner:ci
LIB_IMAGE as pumba 0.6.5

2019-12-13 10:57 UTC, ksatchit commented on docs/pod-network-latency.md
> +
With latest changes to the network chaos experiments, an iproute2 container is necessary to inject the chaos (was done to facilitate the cases where app containers' base images do not have tc installed)

2019-12-13 10:59 UTC, ksatchit commented on docs/pod-network-latency.md
> +
Probably we could add the note about minikube support in the README on we have more info/test results that @LaumiH is helping us with..

2019-12-13 11:00 UTC, ksatchit commented on docs/pod-network-latency.md
> +          value: "nginx-deploy-container" #Container name where chaos has to be injected
nginx

2019-12-13 12:05 UTC, ksatchit submitted a review, later dismissed

2019-12-13 13:17 UTC, ajeshbaby approved these changes
LGTM, Branch is out of date this needs to be handled

2019-12-13 13:18 UTC, merged

2019-12-17 09:13 UTC, LaumiH commented on docs/pod-network-latency.md
> +
Sorry, I was on sick leave yesterday. I tested it with the newest minikube, it works *without* privileged containers now, with pumba 0.6.5.

test pod:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busy3
  name: busy3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy3
  template:
    metadata:
       labels:
        app: busy3
    spec:
      containers:
        - image: debian
          name: busy-3
          command: [ "/bin/bash", "-c", "sleep 10000;exit 0" ]
```
chaosengine:
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine
  namespace: default
spec:
  jobCleanUpPolicy: retain
  monitoring: false
  appinfo: 
    appns: default
    applabel: 'app=busy3'
    appkind: deployment 
  chaosServiceAccount: 'busy'
  experiments:
    - name: pod-network-loss
      spec:
        components:
        - name: TARGET_CONTAINER
          value: 'busy-3'
        - name: NETWORK_INTERFACE
          value: 'eth0'
        - name: TOTAL_CHAOS_DURATION
          value: '40000' #ms
        - name: LIB
          value: 'pumba'
        - name: LIB_IMAGE
          value: 'gaiaadm/pumba:latest'
```