[docs] - (generic) CPU Hog experiment
litmuschaos/v1-litmus-docs pull request #113
Opened 2019-12-12 08:29 UTC by uditgaurav

Signed-off-by: udit <uditgaurav@gmail.com>

- docs for CPU Hog generic experiment

2019-12-12 08:38 UTC, amitbhatt818 submitted a review, later dismissed
/lgtm

2019-12-12 08:54 UTC, amitbhatt818 submitted a review, later dismissed

2019-12-12 13:12 UTC, imrajdas submitted a review, later dismissed
Looks good

2019-12-12 13:16 UTC, ksatchit commented on docs/cpu-hog.md
> +sidebar_label: CPU Hog
See how we are formatting the side bar labels of other experiments. Can this be: `CPU Hog`

2019-12-12 13:17 UTC, ksatchit commented on docs/cpu-hog.md
> +| Generic   | Give a CPU spike on kubernetes Node | GKE, Minikube, OpenShift(Baremetal)                               |
Exhaust CPU resources on the Kubernetes Node

2019-12-12 13:29 UTC, ksatchit commented on docs/cpu-hog.md
> +- This experiment is used to inject a CPU spike chaos on a Kubernetes Node - which will help us to read the scenario where the node consumes the CPU equal to the CPU capacity to that node
This experiment causes CPU resource exhaustion on the Kubernetes node. The experiment aims to verify resiliency of applications whose replicas may be evicted on account on nodes turning unschedulable (`Not Ready`) due to lack of

2019-12-12 13:43 UTC, ksatchit commented on docs/cpu-hog.md
> +- A stress tool is used to inject different kind of resource stress - such as CPU on the Kubernetes node. The stress command is executed in one of our daemonset pod (scheduled on the same node where
The CPU chaos is injected using a daemonset running the linux `stress` tool (a workload generator). The chaos is effected for a period equalling the TOTAL_CHAOS_DURATION.

2019-12-12 13:44 UTC, ksatchit commented on docs/cpu-hog.md
> +- Tests the pod's behavior (application & services) running on the node which is under chaos experiment
application implies services. Can be reframed as: 

Tests application resiliency upon replica evictions caused due to lack of CPU resources

2019-12-12 13:44 UTC, ksatchit commented on docs/cpu-hog.md
> +- CPU Hog can be effected using one of these chaos libraries: `litmus`, `powerfulseal`
How powerfulseal?

2019-12-12 13:45 UTC, ksatchit commented on docs/cpu-hog.md
> +- The desired chaos library can be selected by setting one of the above options as value for the env variable `LIB`
We don't have options for `LIB` other than `litmus`.

2019-12-12 13:46 UTC, ksatchit commented on docs/cpu-hog.md
> +- View the CPU spike on the application node by setting up a watch on the node
setting up a watch of the CPU consumed by nodes in the Kubernetes Cluster

2019-12-12 13:47 UTC, ksatchit commented on docs/cpu-hog.md
> +| Generic   | Give a CPU spike on kubernetes Node | GKE, Minikube, OpenShift(Baremetal)                               |
Can we restrict this only to GKE? That is the only platform where self-recovery of nodes is possible.

2019-12-12 13:48 UTC, ksatchit commented on docs/cpu-hog.md
> +    - name: pod-delete
We are doing CPU chaos right?

2019-12-12 13:50 UTC, ksatchit commented on docs/cpu-hog.md
> +
Can we add a note here saying there should be administrative access to the platform on which the Kubernetes cluster is hosted, as the recovery of the affected could be manual. Example `gcloud` access to the project.

2019-12-12 13:50 UTC, ksatchit commented on docs/cpu-hog.md
> +| LIB                   | The chaos lib used to inject the chaos                       | Optional  | Defaults to `litmus`. Supported: `litmus`, `powerfulseal`                         |
Only litmus supported

2019-12-12 13:50 UTC, ksatchit commented on docs/cpu-hog.md
> +| PLATFORM              | The platform on which the chaos experiment will run          | Optional  | Defaults to ANY                                                                   |
Lets make it GKE only.

2019-12-12 13:52 UTC, ksatchit requested changes
Have been busy with a bucket load of PRs today, hence the delay. Have requested changes on the basis of readability as well as usability. Please check.

2019-12-12 18:48 UTC, uditgaurav commented on docs/cpu-hog.md
> +| Generic   | Give a CPU spike on kubernetes Node | GKE, Minikube, OpenShift(Baremetal)                               |
true @ksatchit  done!

2019-12-12 19:08 UTC, uditgaurav commented on docs/cpu-hog.md
> +sidebar_label: CPU Hog
sidebar_labels for container kill and pod delete are not formatted and are written like this only. Do I need to change this?

2019-12-13 04:18 UTC, ksatchit approved these changes
Thanks! /lgtm

2019-12-13 04:19 UTC, merged