(feat)docs: Added docs for openebs experiments
litmuschaos/v1-litmus-docs pull request #114
Opened 2019-12-12 11:07 UTC by somesh2905

Signed-off-by: somesh kumar <somesh.kumar@mayadata.io>
1. Added docs for openebs experiments
- openebs-target-network-loss
- openebs-pool-pod-failure
- openebs-pool-container-failure
2. Resolved typo in openebs-target-network-delay docs

2019-12-12 12:01 UTC, ispeakc0de requested changes

2019-12-12 12:01 UTC, ispeakc0de commented on docs/openebs-pool-container-failure.md
> +id: openebs-pool-container-failure
For containers, we are following container kill convention. Can you please change it to `openebs-pool-container-kill`

2019-12-12 12:01 UTC, ispeakc0de commented on docs/openebs-pool-container-failure.md
> +sidebar_label: OpenEBS Pool Container Failure
same as above

2019-12-12 12:01 UTC, ispeakc0de commented on docs/openebs-pool-container-failure.md
> +| Variables             | Description                                                  | Type      | Notes                                                      |
Can you please add lib image env variable?

2019-12-12 12:01 UTC, ispeakc0de commented on docs/openebs-pool-container-failure.md
> +- Container kill is achieved using the pumba chaos library in case of docker runtime, & litmuslib using crictl tool in case of containerd runtime.
Is this experiment support containerd runtime?

2019-12-12 12:01 UTC, ispeakc0de commented on docs/openebs-pool-container-failure.md
> +          - name: FORCE
is this env required?

2019-12-12 12:01 UTC, ispeakc0de commented on docs/openebs-target-network-loss.md
> +- Ensure that the Litmus Chaos Operator is running
Can you please provide the link of operator.yaml https://github.com/litmuschaos/chaos-operator/blob/master/deploy/operator.yaml

2019-12-12 12:01 UTC, shubhamchaudhary commented on docs/openebs-target-network-loss.md
> +| CONTAINER_RUNTIME     | The container runtime used in the Kubernetes Cluster         | Optional  | Defaults to `docker`. Supported: `docker`                  |
We don't have container_runtime env in job.yaml

2019-12-12 12:01 UTC, shubhamchaudhary commented on docs/openebs-target-network-loss.md
> +| TARGET_CONTAINER      | The container into which delays are injected in the storage controller pod  | Optional  | Defaults to `cstor-istgt`                   |
this field is also not present inside job

2019-12-12 12:01 UTC, shubhamchaudhary commented on docs/openebs-target-network-loss.md
> +| Variables             | Description                                                  | Type      | Notes                                                      |
please add NETWORK_PACKET_LOSS_PERCENTAGE env variable here

2019-12-12 13:22 UTC, somesh2905 commented on docs/openebs-pool-container-failure.md
> +id: openebs-pool-container-failure
@shubhamchaudhary  Chaosexperiment cr is getting created with this name only. So, should I change or not

2019-12-12 13:54 UTC, w3aman requested changes

2019-12-12 13:54 UTC, w3aman commented on docs/openebs-pool-container-failure.md
> +- This scenario validates the behaviour of stateful applications and OpenEBS data plane upon forced termination of the target pod container
use targeted pool pod container instead of target pod container

2019-12-12 13:59 UTC, somesh2905 commented on docs/openebs-pool-container-failure.md
> +id: openebs-pool-container-failure
modified

2019-12-12 13:59 UTC, somesh2905 commented on docs/openebs-pool-container-failure.md
> +| Variables             | Description                                                  | Type      | Notes                                                      |
added

2019-12-12 13:59 UTC, somesh2905 commented on docs/openebs-pool-container-failure.md
> +- Container kill is achieved using the pumba chaos library in case of docker runtime, & litmuslib using crictl tool in case of containerd runtime.
no, removed

2019-12-12 14:00 UTC, somesh2905 commented on docs/openebs-target-network-loss.md
> +- Ensure that the Litmus Chaos Operator is running
added

2019-12-13 05:17 UTC, w3aman submitted a review, later dismissed
/lgtm

2019-12-13 07:21 UTC, ispeakc0de submitted a review, later dismissed

2019-12-13 13:07 UTC, rajdas98 commented on docs/openebs-pool-container-failure.md
> +If the experiment tunable DATA_PERSISTENCE is set to 'enabled':
use `DATA_PERSISTENCE`

2019-12-13 13:10 UTC, ajeshbaby approved these changes
LGTM

2019-12-13 13:11 UTC, ksatchit approved these changes

2019-12-13 13:15 UTC, merged