(docs): Adding coredns pod delete doc
litmuschaos/v1-litmus-docs pull request #137
Opened 2020-01-07 07:16 UTC by rajdas98

- Adding coredns pod delete doc

2020-01-07 11:23 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +| CoreDNS   | CoreDNS pod delete experiment | KubeADM, Minikube  |
```suggestion
| CoreDNS   | CoreDNS pod delete experiment | Kubeadm, Minikube  |
```

2020-01-07 11:24 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +- Ensure that the `coredns-pod-delete` experiment resource is available in the cluster. If not, install from [here](https://hub.litmuschaos.io/api/chaos?file=charts/coredns/coredns-pod-delete/experim
lets add command to check (refer: drain node)

2020-01-07 11:25 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +- Service resolution checks by deploying a dummy nginx application
```suggestion
- Service resolution works successfully as determined by deploying a sample nginx application
```

2020-01-07 11:25 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +- Service resolution checks by deploying a dummy nginx application
we can add above line and also about the liveness app

2020-01-07 11:27 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +- Deletion of CoreDNS pod will failed the kubernetes service resolution.
do we need this? if the CoreDNS deployment is not resilient (say, not enough replicas), then service resolution will be failed.

2020-01-07 11:28 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +- Provide the application info in `spec.appinfo`
comment - about coreDNS ns (kube-system), labels

2020-01-07 11:28 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +  name: engine-nginx
engine-coredns

2020-01-07 11:29 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +  `watch -n 1 kubectl get pods -n <chaos-namespace>`
may also want to check coreDNS pods health in kube-system

2020-01-07 11:29 UTC, ksatchit commented on docs/disk-loss.md
> +  name: cloud-secret
:+1:

2020-01-08 15:46 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +- Service resolution will failed if coredns replicas will not present.
Will fail if coredns replicas are not present

2020-01-08 15:47 UTC, ksatchit commented on docs/coredns-pod-delete.md
> +- Follow the steps in the sections below to prepare the ChaosEngine & execute the experiment.
There is a slightly different line we are using here - pls refer other experiments

2020-01-08 17:08 UTC, chandankumar4 commented on docs/coredns-pod-delete.md
> +
can we have the list of all supported variables here like what you have mentioned in the example of chaosengine yaml

2020-01-09 09:16 UTC, amitbhatt818 requested changes

2020-01-09 09:16 UTC, amitbhatt818 commented on docs/coredns-pod-delete.md
> +- Ensure that Litmus is install. If not, install from [here](https://docs.litmuschaos.io/docs/getstarted/)
```Ensure that the Litmus Chaos Operator is running by executing `kubectl get pods` in operator namespace (typically, `litmus`). If not, install from [here](https://github.com/litmuschaos/chaos-operator/blob/master/deploy/operator.yaml)```
Use this line @rajdas98

2020-01-09 09:16 UTC, amitbhatt818 commented on docs/coredns-pod-delete.md
> +       image: litmuschaos/ansible-runner:ci
```components:
    runner:
      image: "litmuschaos/chaos-executor:1.0.0"
      type: "go"``` 
Use this here for go executer

2020-01-09 09:16 UTC, amitbhatt818 commented on docs/coredns-pod-delete.md
> +  chaosType: 'infra'    # It can be infra only
comment should come above the line

2020-01-09 11:03 UTC, chandankumar4 commented on docs/coredns-pod-delete.md
> +- Ensure that the Litmus Chaos Operator is running by executing `kubectl get pods` in operator namespace (typically, `litmus`). If not, install from [here](https://github.com/litmuschaos/chaos-operat
Update the operator link with latest from litmuschaos/pages

2020-01-09 11:05 UTC, ksatchit submitted a review, later dismissed

2020-01-09 11:09 UTC, chandankumar4 commented on docs/coredns-pod-delete.md
> +| CHAOS_NAMESPACE       | This is a chaos namespace which will create all infra chaos resources in that namespace	| Mandatory | Default to kube-system |
```suggestion
| CHAOS_NAMESPACE       | This is a chaos namespace which will create all infra chaos resources in that namespace	| Mandatory | Default to `kube-system` |
```

2020-01-09 11:09 UTC, chandankumar4 commented on docs/coredns-pod-delete.md
> +| APP_KIND              | This is describe the application Kind | Mandatory | Mandatory | Defaults to Deployment |
```suggestion
| APP_KIND              | This is describe the application Kind | Mandatory | Mandatory | Defaults to `Deployment` | 
```

2020-01-09 11:10 UTC, chandankumar4 commented on docs/coredns-pod-delete.md
> +| APP_LABEL             | Unique Labels in `key=value` format of application deployment	 | Mandatory | Defaults to k8s-app=kube-dns |
```suggestion
| APP_LABEL             | Unique Labels in `key=value` format of application deployment	 | Mandatory | Defaults to `k8s-app=kube-dns` |
```

2020-01-09 11:10 UTC, chandankumar4 commented on docs/coredns-pod-delete.md
> +| APP_NAMESPACE         | Namespace in which application pods are deployed	  | Mandatory | Defaults to kube-system |
```suggestion
| APP_NAMESPACE         | Namespace in which application pods are deployed	  | Mandatory | Defaults to `kube-system` |
```

2020-01-09 11:16 UTC, ksatchit approved these changes

2020-01-09 11:16 UTC, chandankumar4 approved these changes
/lgtm

2020-01-09 11:16 UTC, amitbhatt818 approved these changes
/lgtm

2020-01-09 11:18 UTC, merged