(feat): Add embedmd commands for adding rbac and engine
litmuschaos/v1-litmus-docs pull request #194
Opened 2020-02-12 07:49 UTC by uditgaurav

Signed-off-by: Udit Gaurav uditgaurav@gmail.com

Add embedmd commands for adding rbac and engine

2020-02-12 07:52 UTC, ksatchit submitted a review, later dismissed

2020-02-12 16:36 UTC, ispeakc0de requested changes

2020-02-12 16:36 UTC, shubhamchaudhary commented on docs/node-cpu-hog.md
> +  annotationCheck: 'false'
Why it is coming twice?

2020-02-12 16:36 UTC, shubhamchaudhary commented on docs/node-cpu-hog.md
>        spec:
it should be node-cpu-hog?

2020-02-12 16:36 UTC, shubhamchaudhary commented on docs/pod-network-loss.md
> +apiVersion: v1
Can you pls add chaosEngine here instead of rbac?

2020-02-13 12:19 UTC, ksatchit commented on docs/getstarted.md
> +## Use embedmd command before commiting changes
This will go inside README

2020-02-13 12:19 UTC, ksatchit commented on docs/getstarted.md
>  kubectl describe chaosresult engine-nginx-pod-delete
make it engine-nginx-container-kill

2020-02-13 12:20 UTC, ksatchit commented on docs/getstarted.md
>  ### Annotate your application
instead of myserver use nginx

2020-02-14 19:27 UTC, ksatchit approved these changes

2020-02-14 19:27 UTC, merged