(feat) add chaosengine construction doc
litmuschaos/v1-litmus-docs pull request #214
Opened 2020-02-26 16:33 UTC by ksatchit

- Introduce a concepts section with a doc on construction of chaosengine manifest

Signed-off-by: ksatchit <ksatchit@mayadata.io>

2020-02-26 18:21 UTC, ispeakc0de requested changes

2020-02-26 18:21 UTC, ispeakc0de commented on docs/chaosengine-concepts.md
> +  <td><code>.spec.components.runner.image</code></td>
Why are we not adding `.spec.components.monitor.image` field?

2020-02-26 18:21 UTC, ispeakc0de commented on docs/chaosengine-concepts.md
> +  <td><code>.spec.appinfo.applabel</code></td>
Why are we not adding `.spec.appinfo.appkind` field? As we are using appkind in the annotationCheck

2020-02-27 00:28 UTC, uditgaurav commented on docs/chaosengine-concepts.md
> +</tr>
By default, we use to give our image?

2020-02-27 00:31 UTC, uditgaurav commented on docs/chaosengine-concepts.md
> +  <td><i>user-defined</i></td>
user-defined (type: string)

2020-02-27 00:39 UTC, uditgaurav commented on docs/chaosengine-concepts.md
> +<td><code>Always</code>, <code>IfNotPresent</code></td>
The Range of image pull policy can be never also. In such a case, we should add one line in the notes pointing it should not be never.

2020-02-27 00:44 UTC, uditgaurav commented on docs/chaosengine-concepts.md
> +  <td><code>active</code></td>
If we have given the default value i.e `active` then why it is mandatory?

2020-02-27 00:51 UTC, uditgaurav commented on docs/chaosengine-concepts.md
> +  <td><code>active</code></td>
unlike jobCleanupPolicy

2020-02-27 05:22 UTC, ksatchit commented on docs/chaosengine-concepts.md
> +</tr>
this is no longer a part of the default example specs right now, as can be seen on chaos-charts. Also the default varies based on operator manifest, i.e., we enforce a default inside code and then on manifest. For the user of the chaosengine -- either of the above can be a "default". Added a note.

2020-02-27 05:23 UTC, ksatchit commented on docs/chaosengine-concepts.md
> +  <td><code>.spec.appinfo.applabel</code></td>
Added this.

2020-02-27 05:23 UTC, ksatchit commented on docs/chaosengine-concepts.md
> +  <td><code>.spec.components.runner.image</code></td>
Don't plan to expose this to users yet. As the monitoring infra/strategy needs to evolve better

2020-02-27 05:24 UTC, ksatchit commented on docs/chaosengine-concepts.md
> +  <td><i>user-defined</i></td>
Done!

2020-02-27 05:26 UTC, ksatchit commented on docs/chaosengine-concepts.md
> +<td><code>Always</code>, <code>IfNotPresent</code></td>
We are exposing a chaosengine "range" of pull policies supported by Litmus for the runner as only Always/IfNotPresent. Never will not supported at all us -- we should enforce this via CRD validation.

2020-02-27 05:28 UTC, ksatchit commented on docs/chaosengine-concepts.md
> +  <td><code>active</code></td>
Here mandatory refers to the *presence of the chaosengine flag* in the spec - not just the values. `engineState` will be mandatory to enforce actual state of engine.

2020-02-27 06:22 UTC, uditgaurav approved these changes
lgtm

2020-02-27 14:13 UTC, ispeakc0de approved these changes
/lgtm

2020-02-27 14:13 UTC, ispeakc0de approved these changes
/lgtm

2020-02-28 10:07 UTC, chandankumar4 approved these changes

2020-02-28 10:07 UTC, merged