Added Administator Mode page inside Advanced Section
litmuschaos/v1-litmus-docs pull request #246
Opened 2020-03-27 11:29 UTC by rahulchheda

Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>

2020-03-27 14:37 UTC, ksatchit commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +Admin Mode is a priviledged mode that LitmusChaos support in order to make SRE's/ Cluster Admins/ Developers life easier.
```suggestion
Admin mode is one of the ways the chaos orchestration is set up in Litmus, wherein all chaos resources (i.e., install time resources like the operator, chaosexperiment CRs, chaosServiceAccount/rbac and runtime resources like chaosengine, chaos-runner & experiment jobs) are setup in a single admin namespace (typically, litmus). In other words, centralized administration of chaos. 

This feature is aimed at making the SRE/Cluster Admins life easier by doing away with setting up chaos pre-requisites on a per namespace basis (which may be more relevant in an autonomous/self-service cluster sharing model in dev environments). 
```

2020-03-27 14:45 UTC, ksatchit commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +This mode helps to induce chaos in different namespaces, by managing all the chaos resources in a single namespace.
```suggestion
This mode typically needs a "wider" & "stronger" ClusterRole, albeit one that is still just a superset of the individual experiment permissions. In this mode, the applications in their respective namespaces are subjected to chaos while the chaos job runs elsewhere, i.e., admin namespace. 
```

2020-03-27 14:45 UTC, ksatchit commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +- apiGroups: ["*"]
Can we recommend superset of all experiments -- `*/*/*` contains just too much beyond what we need.

2020-03-27 14:59 UTC, ksatchit commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +In order to use Admin Mode, you just have to create a ServiceAccount in Chaos Resources Namespace, that has the permissions to perform operations on different kubernetes resources, in different names
```suggestion
In order to use Admin Mode, you just have to create a ServiceAccount in the *admin* or so called *chaos* namespace (`litmus` itself can be used), which is tied to a ClusterRole that has the permissions to perform operations on Kubernetes resources involved in the selected experiments across namespaces.
```

2020-03-27 15:01 UTC, ksatchit commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +Just use this ServiceAccount Name in ChaosEngine chaosServiceAccount, this will let you to have all chaos resources in a single namespace, with chaos being performed on various namespaces.
```suggestion
Use provide this ServiceAccount in ChaosEngine's `.spec.chaosServiceAccount`. 
```

2020-03-27 15:02 UTC, ksatchit commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +  `kubectl describe chaosengine <chaos-engine> -n <chaos-resources-namespace>`
```suggestion
  `kubectl describe chaosengine nginx-chaos -n litmus`
```

2020-03-27 15:03 UTC, ksatchit commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +  `watch -n 1 kubectl get pods -n <application-namespace>`
```suggestion
  `watch -n 1 kubectl get pods -n default`
```

2020-03-27 15:03 UTC, ksatchit commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +  `kubectl describe chaosresult nginx-chaos-pod-delete -n <application-namespace>`
```suggestion
  `kubectl describe chaosresult nginx-chaos-pod-delete -n litmus`
```

2020-03-31 05:24 UTC, ksatchit submitted a review, later dismissed

2020-03-31 06:23 UTC, ispeakc0de requested changes

2020-03-31 06:23 UTC, ispeakc0de commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +Use provide this ServiceAccount in ChaosEngine's `.spec.chaosServiceAccount`.
Provide this ServiceAccount in ChaosEngine's `.spec.chaosServiceAccount`.

2020-03-31 06:23 UTC, ispeakc0de commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +https://litmuschaos.github.io/pages/litmus-admin-rbac.yaml
Can we make this section more descriptive or use embedmd?

2020-03-31 06:23 UTC, ispeakc0de commented on website/sidebars.json
> +      "admin-mode"
Where is this file? Can we create a copy of this file under the docs section also?

2020-03-31 08:00 UTC, ksatchit commented
Lets get one copy of the same in doc master as well.

2020-03-31 08:49 UTC, rahulchheda commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +https://litmuschaos.github.io/pages/litmus-admin-rbac.yaml
Can you help me with embedmd? I dont have knowledge around it

2020-03-31 08:50 UTC, rahulchheda commented on website/sidebars.json
> +      "admin-mode"
No need, this seems to be the main directory structure of docs.

2020-03-31 14:38 UTC, ispeakc0de requested changes

2020-03-31 14:38 UTC, ispeakc0de commented on docs/admin-mode.md
> +https://litmuschaos.github.io/pages/litmus-admin-rbac.yaml
Can you add also embedmd command here ??

2020-03-31 14:45 UTC, ispeakc0de requested changes

2020-03-31 14:45 UTC, ispeakc0de commented on docs/admin-mode.md
> +[embedmd]:# (https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/container-kill/rbac.yaml yaml)
This is please use the correct link, https://raw.githubusercontent.com/litmuschaos/pages/master/docs/litmus-admin-rbac.yaml

2020-03-31 14:45 UTC, ispeakc0de commented on website/versioned_docs/version-1.2.0/admin-mode.md
> +[embedmd]:# (https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/container-kill/rbac.yaml yaml)
Can you please use a correct link: https://raw.githubusercontent.com/litmuschaos/pages/master/docs/litmus-admin-rbac.yaml

2020-03-31 14:51 UTC, ispeakc0de submitted a review, later dismissed
/lgtm

2020-03-31 15:01 UTC, ksatchit approved these changes

2020-03-31 15:02 UTC, merged