core(update): Add NODE_CPU_CORE variable in node-cpu-hog docs and embedmd run
litmuschaos/v1-litmus-docs pull request #271
Opened 2020-05-11 10:01 UTC by uditgaurav

**Why do we need this?**

- This PR is for adding the `NODE_CPU_CORE` variable in the docs section of the node-cpu-hog experiment. A feature was added in litmus `1.3` - that a custom cpu cores can also be provided to run the node cpu hog chaos but this parameter was missing in the docs section. 
- It also contains the embedmd run output.

issue - https://github.com/litmuschaos/litmus/issues/1498
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>

2020-05-11 10:05 UTC, ispeakc0de requested changes

2020-05-11 10:05 UTC, ispeakc0de commented on docs/container-kill.md
> +            - name: TOTAL_CHAOS_DURATION
Add these envs in `Supported Experiment Tunables` section too

2020-05-11 10:19 UTC, ispeakc0de requested changes

2020-05-11 10:19 UTC, ispeakc0de commented on docs/container-kill.md
> +    <td> Time interval b/w two successive container failures (in sec) </td>
Time interval b/w two successive container kill (in sec)

2020-05-11 10:19 UTC, ispeakc0de commented on docs/container-kill.md
> +    <td> The time duration for chaos insertion (seconds) </td>
The time duration for chaos injection (seconds)

2020-05-11 10:19 UTC, ispeakc0de commented on docs/container-kill.md
> +    <td> Defaults to 20s.Overall run duration of the experiment may exceed the TOTAL_CHAOS_DURATION by a few min </td>
Not a case for this experiment actually.. (Overall run duration of the experiment may exceed the TOTAL_CHAOS_DURATION by a few min)

2020-05-11 10:22 UTC, ispeakc0de approved these changes

2020-05-12 11:32 UTC, ksatchit approved these changes

2020-05-12 11:32 UTC, merged