chore(experiment): Add docs for node service kill experiment
litmuschaos/v1-litmus-docs pull request #289
Opened 2020-06-14 15:25 UTC by uditgaurav

Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
- Adding kubelet service kill chaos experiment docs

2020-06-14 15:45 UTC, ispeakc0de requested changes

2020-06-14 15:45 UTC, ispeakc0de commented on docs/kubelet-service-kill.md
> +    <td> GKE, EKS </td>
Can we make them same as csv file?

2020-06-14 15:45 UTC, ispeakc0de commented on docs/kubelet-service-kill.md
> +- Application Node is healthy before chaos injection
we are checking for the application status in pre/post chaos as well?

2020-06-14 15:45 UTC, ispeakc0de commented on docs/kubelet-service-kill.md
> +- The kubelet service kill has been injected gracefully on a  node to make it unschedulable for a certain TOTAL_CHAOS_DURATION. The application node should be healthy once chaos is stopped and the se
The kubelet service has been stopped/killed on a node to make it unschedulable for a certain duration say `TOTAL_CHAOS_DURATION`. The application node should be healthy after the chaos injection and the services should be reaccessable

2020-06-14 15:45 UTC, ispeakc0de commented on docs/kubelet-service-kill.md
> +    <td> Period to wait before injection of chaos in sec </td>
Period to wait before & after injection of chaos in sec

2020-06-14 15:50 UTC, uditgaurav commented on docs/kubelet-service-kill.md
> +- Application Node is healthy before chaos injection
its application node

2020-06-14 15:51 UTC, ispeakc0de commented on docs/kubelet-service-kill.md
> +- Application Node is healthy before chaos injection
This is the entry criteria right?
https://github.com/litmuschaos/litmus/blob/master/experiments/generic/kubelet_service_kill/kubelet_service_kill_ansible_logic.yml#L54

2020-06-14 16:21 UTC, ispeakc0de commented on docs/kubelet-service-kill.md
> +- The kubelet service has been stopped/killed on a node to make it unschedulable for a certain duration sai.e `TOTAL_CHAOS_DURATION`. The application node should be healthy after the chaos injection
sai.e ?

2020-06-14 16:21 UTC, ispeakc0de commented on docs/kubelet-service-kill.md
> +- Application pods will be healthy post chaos injection.
Application pods and the node should be healthy post chaos injection

2020-06-14 16:21 UTC, ispeakc0de commented on docs/kubelet-service-kill.md
> +- Application pods are healthy on the respective Nodes before chaos injection.
Application pods should be healthy before chaos injection

2020-06-14 18:17 UTC, ispeakc0de approved these changes

2020-06-15 03:43 UTC, imrajdas requested changes

2020-06-15 03:43 UTC, rajdas98 commented on docs/kubelet-service-kill.md
> +  name: kubelet-service-kill
This service account name is not using in chaosengine spec

2020-06-15 03:43 UTC, rajdas98 commented on docs/kubelet-service-kill.md
> +  name: nginx-chaos
name should be kubelet-chaos. Change it in other places

2020-06-15 03:43 UTC, rajdas98 commented on docs/kubelet-service-kill.md
> +- Application pods should be healthy before chaos injection.
- Application pods should be healthy before chaos injection.
- Nodes should be healthy before chaos injection

2020-06-15 03:43 UTC, rajdas98 commented on docs/kubelet-service-kill.md
> +- Application pods and the node should be healthy post chaos injection.
- Application pods should be healthy after chaos injection.
- Nodes should be healthy after chaos injection

2020-06-15 12:52 UTC, ksatchit approved these changes

2020-06-15 12:52 UTC, merged