Feature (Docs): Adding documentation for Docker Service Kill Experiment
litmuschaos/v1-litmus-docs pull request #312
Opened 2020-07-13 15:26 UTC by ghoshankur1983

Signed-off-by: Udit Gaurav udit.gaurav@mayadata.io

Adding the Documentation for Docker Service Kill experiment.

2020-07-13 15:52 UTC, ispeakc0de requested changes

2020-07-13 15:52 UTC, ispeakc0de commented on docs/docker-service-kill.md
> +- Ensure that the `docker-service-kill` experiment resource is available in the cluster  by executing                         `kubectl get chaosexperiments` in the desired namespace. If not, install
can we check for the hub link? it should be 1.6.0

2020-07-14 07:26 UTC, ghoshankur1983 commented
Added the change. Please close the PR if found suitable.

2020-07-14 07:29 UTC, uditgaurav submitted a review, later dismissed
lgtm

2020-07-14 11:23 UTC, ispeakc0de commented
@ghoshankur1983 Charts PR has been merged. Can you please embedded the chaos-engine & RBAC for this doc. Please run `embedmd -w docs/docker-service-kill.md`  --- to install the embedmd use `go get github.com/campoy/embedmd`

2020-07-14 12:58 UTC, ghoshankur1983 commented
I had performed the steps. However I do not know what to expect post running the steps.

2020-07-14 15:50 UTC, ispeakc0de commented
@ghoshankur1983 Yes, the expected behavior is same as you are getting for RBAC. It will embed the corresponding manifest here. But I am unable to see a few sections like: `Sample ChaosEngine Manifest`, `Supported Experiment Tunables and `Prepare ChaosEngine`
`

2020-07-14 16:16 UTC, uditgaurav commented on docs/docker-service-kill.md
> +
There should be one chaosengine link here as well like this:
`[embedmd]:# (https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/docker-service-kill/engine.yaml yaml)`
and after doing embedmd it should as show yaml snipt of engine.yaml

2020-07-15 07:16 UTC, uditgaurav approved these changes

2020-07-15 07:16 UTC, ispeakc0de approved these changes

2020-07-15 07:17 UTC, ksatchit approved these changes

2020-07-15 07:18 UTC, merged