docs(probe): Adding the get-started docs for the probes
litmuschaos/v1-litmus-docs pull request #344
Opened 2020-09-04 09:34 UTC by ispeakc0de

Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>

**What this PR does / why we need it**:

-  Adding the get-started docs for the probes

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Labelled this PR & related issue with `documentation` tag

2020-09-09 10:01 UTC, ksatchit approved these changes, later dismissed

2020-09-09 10:09 UTC, ksatchit approved these changes, later dismissed

2020-09-09 10:13 UTC, ksatchit commented
@k8s-dev @divya-mohan0209 do you have any thoughts around how this doc is structured? We have made some changes to it since the initial version.

2020-09-10 03:13 UTC, divya-mohan0209 requested changes
- Minor grammar + spelling edits.
- Clarity requested in sentences containing technical features.
- @ksatchit @k8s-dev : Clarity on whether PascalCase or camelCase needs to be used for naming conventions. A good primer can be found in this medium blog: https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +Litmus probes can be defined as “pluggable” checks you can define within the ChaosEngine for any chaos experiment. The experiment pods execute these checks based on the mode they are defined in & fac
"Litmus probes can be defined as “pluggable” checks you can define within the ChaosEngine for any chaos experiment.  " Possible rewrite to: "Litmus probes are pluggable checks that can be defined within the ChaosEngine for any chaos experiment".

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +These probes can be used in isolation or in several combinations to achieve the desired checks. While the httpProbe & k8sProbe are fully declarative in the way they are conceived, the cmdProbe expect
"While the httpProbe & k8sProbe are fully declarative in the way they are conceived " - What exactly is being communicated here?

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +- **retry:** The number of times a check is re-run upon failure in the first attempt, before declaring the probe status as failed.
Comma not required

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +The cmdProbe allows developers to run shell commands and match the resulting output as part of the entry/exit criteria. The intent behind this probe is to allow users to implement a non-standard, imp
"Say, you are looking for specific data within a database, parse the value out of a JSON blob being dumped into a certain path, or check for the existence of a particular string in a service log - the cmdProbe can enable you to check this. "

Possible rewrite to: 

"For example, the cmdProbe enables you to check for specific data within a database, parse the value out of a JSON blob being dumped into a certain path or check for the existence of a particular string in the service logs."

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +The cmdProbe allows developers to run shell commands and match the resulting output as part of the entry/exit criteria. The intent behind this probe is to allow users to implement a non-standard, imp
"The intent behind this probe is to allow users to implement a non-standard, imperative way to express their hypothesis"

Possible rewrite to:

The intent behind this probe was to allow users to implement a non-standard & imperative way for expressing their hypothesis.

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +And precisely in order to support this behavior, the probe supports an inline mode in which the command is run from within the experiment image as well as a  source mode, where the command execution
"And precisely in order to support this behavior, the probe supports an inline mode in which the command is run from within the experiment image as well as a  source mode, where the command execution is carried out from within a new pod whose image can be specified"

Possible rewrite to:

"In order to enable this behaviour, the probe supports an inline mode in which the command is run from within the experiment image as well as a  source mode, where the command execution is carried out from within a new pod whose image can be specified."

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +And precisely in order to support this behavior, the probe supports an inline mode in which the command is run from within the experiment image as well as a  source mode, where the command execution
"The cmdProbe can be defined at `.spec.experiments[].spec.cmdProbe` the path inside the chaosengine." -- It's not clear as to what is being conveyed with this statement. Is `.spec.experiments[].spec.cmdProbe` the path? Or is there something else you wish to convey?

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +With the proliferation of custom resources & operators, especially in the case of stateful applications, the steady-state is manifested as status parameters/flags within Kubernetes resources. k8sProb
"the k8sProbe can be defined at `.spec.experiments[].spec.k8sProbe` the path inside chaosengine."

Minor edit: Capitalization of t at the beginning of the sentence

2020-09-10 03:13 UTC, divya-mohan0209 commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +The pass criteria for the experiment is a logical AND function of all the probes defined in the ChaosEngine as well as inbuilt entry/exit criteria. Failure of either indicates a failed hypothesis and
"The pass criteria for the experiment is a logical AND function of all the probes defined in the ChaosEngine as well as inbuilt entry/exit criteria."

Minor grammar edit + rewording:

"The pass criteria for an experiment is the logical conjunction of all probes defined in the ChaosEngine and an inbuilt entry/exit criteria."

2020-09-10 04:20 UTC, ksatchit commented on website/versioned_docs/version-1.7.0/litmus-probe.md
> +These probes can be used in isolation or in several combinations to achieve the desired checks. While the httpProbe & k8sProbe are fully declarative in the way they are conceived, the cmdProbe expect
The probes are being described as a "declarative" approach to define chaos hypothesis, since they are expressed as schema within the chaosengine CR. The httpProbe & k8sProbe have fields/attributes that just describe the desired outcome (a feature of anything purely "declarative") while cmdProbe - is a bit of a mix of both: declarative intent (probe properties and desired outcome is mentioned) + imperative action (the heart of the cmdProbe is the shell command itself).  

The above para intends to bring out this difference. Somewhere in this doc, we are also drawing reference to the ansible command/shell module which shares a similar philosophy as above.

2020-09-10 04:21 UTC, ksatchit commented
Thanks @divya-mohan0209 ! @ispeakc0de - FYA!

2020-09-10 04:41 UTC, ksatchit commented
> * Minor grammar + spelling edits.
> * Clarity requested in sentences containing technical features.
> * @ksatchit @k8s-dev : Clarity on whether PascalCase or camelCase needs to be used for naming conventions. A good primer can be found in this medium blog: https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841

I suppose camelCase is I would recommend, @divya-mohan0209 - to keep it consistent with the CR spec.

2020-09-10 13:37 UTC, divya-mohan0209 reviewed
chaosEngine is capitalized as camelCase in some instances & PascalCase in others. Please can we ensure all naming conventions follow either one - camelCase or PascalCase

2020-09-11 05:01 UTC, ksatchit commented
The CR Kind is always in PascalCase, while the spec attributes are typically camelCase.  We can follow the convention used in the CR Spec. The Kubernetes docs also use the PascalCase when referring to native resources, while the attributes are referred in camelCase (and often represented as `codeBlocks`.  We can follow this practice too.

2020-09-14 04:52 UTC, divya-mohan0209 approved these changes
LGTM

2020-09-14 04:55 UTC, ksatchit approved these changes
LGTM

2020-09-14 04:58 UTC, merged