Contribution guide for litmus-docs
litmuschaos/v1-litmus-docs pull request #345
Opened 2020-09-07 02:12 UTC by k8s-dev

This commit has process about getting started to contribute towards
litmus-docs repo.

Fixes # https://github.com/litmuschaos/litmus/issues/1942 
Signed-off-by: Jayesh Kumar Tank <k8s.cncf@gmail.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Labelled this PR & related issue with `documentation` tag

2020-09-07 13:50 UTC, ksatchit commented on CONTRIBUTING.md
> +* Manage and publish the documentation parts of the Litmus release cycle
docs framework, build process.

2020-09-07 13:51 UTC, ksatchit commented on CONTRIBUTING.md
> +* Find an issue to work on or create a new issue. The issues are maintained at [litmuschaos/litmus](https://github.com/litmuschaos/litmus/issues). For new contributors, you can pick up from a list of
area/litmus-docs

2020-09-07 13:52 UTC, ksatchit commented on CONTRIBUTING.md
> +* Create a branch from where you want to base your work (usually master).
Ref: Standard git OSS procedure (link)

2020-09-07 13:55 UTC, ksatchit commented on CONTRIBUTING.md
> +* Make your changes, test locally, see preview by starting server and seeing in Preview Mode.
Add step to view preview (comment w/ preview link) and escalate if preview fails.

2020-09-07 13:59 UTC, ksatchit commented on CONTRIBUTING.md
> +* Commit your changes by making sure the commit messages convey the need and notes about the commit.
Pull the latest version of the kubernetes snippet being used in the doc by using embedmd tool. Ref: https://github.com/litmuschaos/litmus-docs#use-embedmd-command-before-commiting-changes

2020-09-07 13:59 UTC, ksatchit commented on CONTRIBUTING.md
> +* Commit your changes by making sure the commit messages convey the need and notes about the commit.
Ref: http://github.com/campoy/embedmd/

2020-09-14 14:49 UTC, ksatchit commented on CONTRIBUTING.md
> +* Find an issue to work on or create a new issue. The issues are maintained at [litmuschaos/litmus](https://github.com/litmuschaos/litmus/issues). For new contributors, you can pick up from a list of
https://github.com/litmuschaos/litmus/issues?q=is%3Aopen+label%3A%22good+first+issue%22+label%3A%22area%2Flitmus-docs%22

2020-09-14 14:51 UTC, ksatchit commented on CONTRIBUTING.md
> +* Commit your changes by making sure the commit messages convey the need and notes about the commit.
@k8s-dev can we add this too?

2020-09-16 05:25 UTC, divya-mohan0209 requested changes
Minor grammatical + spelling changes. Also, would look at standardizing the way Litmus is capitalized across the documentation (barring links).

2020-09-16 05:25 UTC, divya-mohan0209 commented on CONTRIBUTING.md
> +Litmus is an Apache 2.0 Licensed project and uses the standard GitHub pull requests process to review and accept contributions. We welcomes improvements from all contributors, new and experienced!
Minor grammatical edit: "We welcome improvements from all contributors, new and experienced."

2020-09-16 05:25 UTC, divya-mohan0209 commented on CONTRIBUTING.md
> +* Manage and publish the documentation parts of the Litmus release cycle
Possible rewrite to: Manage & publish documentation as part of the Litmus release cycle.

2020-09-16 07:24 UTC, akria18 submitted a review, later dismissed

2020-09-16 07:24 UTC, akria18 commented on CONTRIBUTING.md
> +Documentation SIG lives [here](https://github.com/litmuschaos/litmus/wiki/Special-Interest-Groups#sig-documentation). Please join the weekly zoom call, introduce yourself and get started!!
SIG documentations are here

2020-09-16 07:24 UTC, akria18 commented on CONTRIBUTING.md
> +Litmus documentation currently runs using [Docusaurus](https://docusaurus.io/) static file generator. [Embedmd](https://github.com/campoy/embedmd/) for embedding source codes into the documentation.
Also, we have integrated Netlify to deploy preview of the change.

2020-09-21 15:49 UTC, ksatchit approved these changes

2020-09-22 10:38 UTC, merged