troubleshooting faq describe chaosresult notfound error added
litmuschaos/v1-litmus-docs pull request #361
Opened 2020-09-25 17:36 UTC by whitetiger1399

Signed-off-by: whitetiger1399 <ritik.srivastava@mayadata.io>

**What this PR does / why we need it**:
the one troubleshooting issue added: delay in the describe chaosresult command initially gives error and user has to wait before it runs successfully. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Labelled this PR & related issue with `documentation` tag

2020-10-01 12:17 UTC, divya-mohan0209 requested changes
- Resource names need to be in PascalCase
- Spec Attributes need to be in camelCase
- The "l" of Litmus needs to be capitalized in every instance.

Please make the changes & resubmit the PR.
@ksatchit @k8s-dev : Please review & suggest if I've missed anything

2020-10-09 09:59 UTC, whitetiger1399 commented
@divya-mohan0209 at the places where "litmus" is in small case it refers to litmus namespace. For the rest at all place where we are referring to  Litmus product, it has capital case "L"

2020-10-15 10:27 UTC, ksatchit commented
> @divya-mohan0209 at the places where "litmus" is in small case it refers to litmus namespace. For the rest at all place where we are referring to Litmus product, it has capital case "L"

Updated as per naming conventions and fixed some broken links!

2020-10-15 10:28 UTC, ksatchit approved these changes

2020-10-15 10:28 UTC, uditgaurav approved these changes

2020-10-15 10:31 UTC, merged