Monitoring Documentation
litmuschaos/v1-litmus-docs pull request #364
Opened 2020-09-28 14:44 UTC by ishangupta-ds

**What this PR does / why we need it**: This PR adds docs for the monitoring aspect of LitmusChaos.

**Which issue this PR fixes**: fixes #363 

**Special notes for your reviewer**: None.

**Checklist:**
-   [x] Fixes #363 
-   [ ] Labelled this PR & related issue with `documentation` tag

2020-09-29 11:19 UTC, ishangupta-ds commented
@ksatchit @umamukkara @divya-mohan0209 @ajeshbaby PTAL.

2020-09-29 11:36 UTC, divya-mohan0209 requested changes
Minor rewording comments added.

2020-09-29 11:36 UTC, divya-mohan0209 commented on docs/monitoring.md
> +Building a hypothesis around steady-state behaviour, varying real-world events, running experiments in production and automating them to run as a workflow in CI pipelines and minimizing the blast rad
Possible reword to: "Building a hypothesis around steady-state behaviour, varying real-world events, running experiments in production, automating them to run as a workflow in CI pipelines, and minimizing the blast radius are some advanced chaos practices. These are all backed by extensive monitoring infrastructure managed by SREs heading IT operations. Monitoring chaos and performance metrics is an observability paradigm providing real-time insights into the four golden signals for monitoring distributed systems namely, latency, traffic, errors, and saturation."

2020-09-29 11:52 UTC, ishangupta-ds commented on docs/monitoring.md
> +Building a hypothesis around steady-state behaviour, varying real-world events, running experiments in production and automating them to run as a workflow in CI pipelines and minimizing the blast rad
surely.. @divya-mohan0209

2020-10-05 10:00 UTC, ishangupta-ds commented
@divya-mohan0209 @ksatchit PTAL.

2020-10-05 10:13 UTC, ksatchit approved these changes

2020-10-05 10:13 UTC, merged