chore(chaosengine): adding imagePullSecrets & resource in engine-concepts
litmuschaos/v1-litmus-docs pull request #376
Opened 2020-10-03 07:52 UTC by ispeakc0de

Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Labelled this PR & related issue with `documentation` tag

2020-10-04 12:29 UTC, divya-mohan0209 requested changes
Please ensure you make the changes per recommendation & adhere to conventions while referring to annotations.

2020-10-04 12:29 UTC, divya-mohan0209 commented on docs/chaosengine-concepts.md
> +  <td>The <code>.components.runner.imagePullSecrets</code> allows developers to specify the <code>imagePullSecret</code> name for chaos-runner. </td>
chaos-runner should be ChaosRunner per the documentation standards we're following.

2020-10-04 12:29 UTC, divya-mohan0209 commented on docs/chaosengine-concepts.md
> +  <td>Specify the resource requirements for the chaos experiment pod</td>
chaos experiment needs to be rewritten as ChaosExperiment per the documentation standard.

2020-10-04 12:29 UTC, divya-mohan0209 commented on docs/chaosengine-concepts.md
> +  <td>The <code>experiment[].spec.components.resources</code> contains the resource requirements for the chaos experiment Pod, where we can provide resource requests and limits for the pod.</td>
chaos experiment needs to be ChaosExperiment per the documentation standard.

2020-10-05 08:02 UTC, ksatchit commented
We can also include spec.component.args - it is missing right now

2020-10-05 08:28 UTC, ksatchit approved these changes

2020-10-05 08:30 UTC, ksatchit commented
PR has been updated with review comments. LGTM

2020-10-05 08:30 UTC, merged