Added more use cases for kubernetes
litmuschaos/v1-litmus-docs pull request #394
Opened 2020-10-16 23:13 UTC by sumitnagal

Signed-off-by: Sumit Nagal <sumit_nagal@intuit.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Signed the commit for DCO to be passed
-   [ ] Labelled this PR & related issue with `documentation` tag

2020-10-19 23:29 UTC, navinjoy submitted a review, later dismissed
LGTM

2020-11-06 16:44 UTC, ksatchit approved these changes

2020-11-06 16:48 UTC, ksatchit requested changes
The versioned docs need the original_id fields. Please refer to other versioned docs for reference. Currently, this causes build failure

2020-11-09 12:48 UTC, ispeakc0de approved these changes

2020-11-09 17:30 UTC, ksatchit commented
Changes made as part of refactor to accommodate these experiments in a different category.

2020-11-09 17:31 UTC, merged