fixed readme
litmuschaos/v1-litmus-docs pull request #57
Opened 2019-10-20 14:11 UTC by kmjayadeep

changes:

- Added setup instructions using docker and docker compose
- Changed nodejs installation instruction to download version 12.x instead of 9.x
- Added missing `npm install` instruction
- Added `package-lock.json` file to repository
- Removed `yarn` instructions to avoid conflicts with `npm`

Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

2019-10-23 07:35 UTC, inyee786 commented on README.md
> +## Manual Setup
can out this step at above, people usually use this for local development and docker-compose is a way of testing the thing, not for development

2019-10-23 07:38 UTC, inyee786 commented
@qiell do we need `package-lock.json` file, as for reactjs project many people use yarnpkg instead of npm

2019-10-23 14:35 UTC, kmjayadeep commented
> @qiell do we need `package-lock.json` file, as for reactjs project many people use yarnpkg instead of npm

These days `npm` are also being used extensively as it supports many of the features `yarn` has. In any case we should use either `npm` or `yarn` but not both. I will create separate PR to make similar change in dockerfile as well.

2019-10-26 00:28 UTC, kmjayadeep commented on README.md
> +## Manual Setup
done

2019-10-30 04:27 UTC, ksatchit submitted a review, later dismissed
/lgtm

2019-10-30 05:34 UTC, chandankumar4 approved these changes

2019-10-30 06:02 UTC, chandankumar4 requested changes
@kmjayadeep, I think we don't require these changes, Can you take a look at this. https://github.com/openebs/openebs-docs (This is also one of the docusaurus projects)

2019-10-30 07:12 UTC, kmjayadeep commented
> @kmjayadeep, I think we don't require these changes, Can you take a look at this. https://github.com/openebs/openebs-docs (This is also one of the docusaurus projects)

Hi @chandankumar4 

1. In openebs-docs also, there are similar issues. `npm install -g yarn` command is provided in readme, but the project is using `npm` and not `yarn`. This can cause conflicts.
2. `package-lock.json` is missing. This is important to be able to resolve to correct dependencies while doing `npm install`
3. `docker-compose` instructions are optional, but it makes development easier

2019-11-03 16:44 UTC, chandankumar4 submitted a review, later dismissed
LGTM
Thanks, @kmjayadeep for your contribution, I updated some of the changes as per required!

2019-11-03 16:59 UTC, chandankumar4 approved these changes

2019-11-03 17:00 UTC, merged